version: '3.1'
services: 

  db:
    image: mysql
    container_name: mysql.dev
    command: mysqld --user=root --verbose --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /apps/docker/mysql:/var/lib/mysql
      - ./mysql/dbsetup.sql:/tmp/dbsetup.sql
      - ./mysql/importdb.sh:/tmp/importdb.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    
  web:
    build: .
    container_name: noderest
    command: npm start
    #volumes:
     # - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=testdb
    depends_on:
     - db
# ipam is removed in version 3, issues with swarm mode
# https://github.com/docker/compose/issues/4474     